### PR TITLE
Add automlx notebooks

### PR DESCRIPTION
**Pull request by jdesanto**
- Added 5 new notebooks with bib sections
- Added new field to bib: "original source"
- Changed logic to allow optional parameters

### CODE REVIEW

**Comment by johnpeach** [comment]
Please do not create WIP PRs. You should be working on your own forked version of the repo and once you have it reviewed and approved then create a PR. Thanks.

**Comment by jdesanto** [comment]
Notebooks in this PR all run with the pre-release AutoMLx v2 conda pack.

**Comment by darenr** [comment]
@jdesanto shouldn't this also include index.json which now has the new notebooks, along with README?

**Comment by jdesanto** [comment]
@darenr I thought the index.json and README were updated automatically anytime there were notebook changes to master. I can rebuild and recommit if not.

**Comment by darenr** [comment]
No, you have to run it. If the notebooks themselves are present then I can run it later. You can easily tell if the index has the notebooks, the readme file has the list (the same list) of notebooks that are present. If you see it in the readme then you'll see it in the index. 

But are the notebooks themselves on GitHub now?

**Pull request merged**
